### ISSUE TITLE
[NSA] Continuous integration

### ISSUE THREAD

**Issue by egnaf** [reckue/note-service-api#4]
Please connect Travis CI to the project.

Add **.travis.yml** to root directory.
```yaml
language: java
jdk: openjdk11
install: true

cache:
  directories:
    - $HOME/.gradle

script:
  - gradle build --refresh-dependencies && cd ..

notifications:
  email:
    recipients:
      - egnaf@yahoo.com
      - hardelele@yahoo.com
    on_success: never
    on_failure: always
```
